# Generated by Django 5.2.7 on 2025-10-20 07:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneproblem',
            options={'ordering': ['name'], 'verbose_name': 'Phone Problem', 'verbose_name_plural': 'Phone Problems'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='additional_discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='additional_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='phonemodel',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='phoneproblem',
            name='display_order',
        ),
        migrations.AddField(
            model_name='order',
            name='website_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Website fixed discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='website_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Website discount percentage on subtotal after item discounts', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='warranty_days',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
