# Generated by Django 5.2.7 on 2025-10-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_phoneproblem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phone Model', 'verbose_name_plural': 'Phone Models'},
        ),
    ]
