# Generated by Django 5.2.7 on 2025-10-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_phonemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
