# Generated by Django 5.2.7 on 2025-10-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_phonemodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
