# Generated by Django 5.2.7 on 2025-10-21 09:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_phonemodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed discount amount', max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage discount applied to subtotal after item discounts', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Discount',
                'verbose_name_plural': 'Website Discounts',
            },
        ),
    ]
