# Generated by Django 5.2.7 on 2025-10-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_websitediscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
