# Generated by Django 5.2.7 on 2025-11-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_phonereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='phone_brands/'),
        ),
    ]
