# Generated by Django 5.2.7 on 2025-11-02 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_phonebrand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonereview',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to='product.orderitem'),
        ),
    ]
