# Generated by Django 5.2.7 on 2025-11-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_phonereview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
