# Generated by Django 5.2.7 on 2025-11-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_order_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'ordering': ['-rank', '-id'], 'verbose_name': 'Phone Model', 'verbose_name_plural': 'Phone Models'},
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
