# Generated by Django 5.2.7 on 2025-11-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_phonemodel_options_phonemodel_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
