# Generated by Django 5.2.7 on 2025-11-17 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_order_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOrderCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_orders', to='product.phonebrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_orders', to='product.phonemodel')),
                ('problem', models.ManyToManyField(related_name='admin_orders', to='product.phoneproblem')),
            ],
            options={
                'verbose_name_plural': 'Admin custom Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
