# Generated by Django 5.2.7 on 2025-11-18 06:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_adminordercreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminordercreate',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed discount amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='adminordercreate',
            name='part_type',
            field=models.CharField(blank=True, choices=[('original', 'Original'), ('duplicate', 'Duplicate')], default='original', max_length=20, null=True),
        ),
    ]
