# Generated by Django 5.2.7 on 2025-10-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newphone', '0002_alter_brand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brands'},
        ),
    ]
