# Generated by Django 5.2.7 on 2025-10-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newphone', '0002_remove_phonebrand_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebrand',
            name='is_active',
        ),
    ]
