# Generated by Django 5.2.7 on 2025-10-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newphone', '0004_alter_brand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='new-phone-model')),
                ('ram', models.CharField(blank=True, max_length=20, null=True)),
                ('memory', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newphone.brand')),
            ],
        ),
    ]
