# Generated by Django 5.2.7 on 2025-10-22 11:27

import django.db.models.deletion
import django_ckeditor_5.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newphone', '0006_remove_model_amount_model_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=100)),
                ('Customer_email', models.EmailField(max_length=254)),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('Phone_name_brand', models.CharField(max_length=100)),
                ('phone_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Brand',
            new_name='PhoneBrand',
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='new-phone-model')),
                ('ram', models.CharField(blank=True, max_length=20, null=True)),
                ('memory', models.CharField(blank=True, max_length=25, null=True)),
                ('main_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discounted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description_title', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('color', models.ManyToManyField(blank=True, to='newphone.phonecolor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('website_discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('website_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newphone.phonemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
