# Generated by Django 5.2.7 on 2025-10-23 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newphone', '0007_phonecolor_shopreview_rename_brand_phonebrand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newphone.phonebrand'),
            preserve_default=False,
        ),
    ]
