# Generated by Django 5.2.7 on 2025-10-26 04:43

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage discount (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Discount',
                'verbose_name_plural': 'Website Discounts',
            },
        ),
        migrations.AlterModelOptions(
            name='newphonebrand',
            options={'ordering': ['name'], 'verbose_name_plural': 'New Phone Brands'},
        ),
        migrations.AlterModelOptions(
            name='newphonecolor',
            options={'ordering': ['name'], 'verbose_name_plural': 'Phone Colors'},
        ),
        migrations.AlterModelOptions(
            name='newphonemodel',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'New Phone Models'},
        ),
        migrations.AlterModelOptions(
            name='newphoneorder',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'New Phone Orders'},
        ),
        migrations.AlterModelOptions(
            name='newphonereview',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Phone Reviews'},
        ),
        migrations.RenameField(
            model_name='newphoneorder',
            old_name='stripe_payment_intent',
            new_name='stripe_charge_id',
        ),
        migrations.RenameField(
            model_name='newphonereview',
            old_name='Customer_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='newphonereview',
            old_name='Customer_name',
            new_name='customer_name',
        ),
        migrations.AlterUniqueTogether(
            name='newphonemodel',
            unique_together={('brand', 'name')},
        ),
        migrations.RemoveField(
            model_name='newphonereview',
            name='Phone_name_brand',
        ),
        migrations.RemoveField(
            model_name='newphonereview',
            name='phone_status',
        ),
        migrations.AddField(
            model_name='newphonebrand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newphonemodel',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='phone_models', to='brandNew.newphonecolor'),
        ),
        migrations.AddField(
            model_name='newphonemodel',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AddField(
            model_name='newphonemodel',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available stock'),
        ),
        migrations.AddField(
            model_name='newphonemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes'),
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=100),
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='order_number',
            field=models.CharField(default=1, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='selected_color',
            field=models.ForeignKey(blank=True, help_text='Color chosen by customer', null=True, on_delete=django.db.models.deletion.PROTECT, to='brandNew.newphonecolor'),
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='shipping_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Unit price × Quantity', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price per unit at time of order', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newphonereview',
            name='phone_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='brandNew.newphonemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newphonebrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newphonebrand',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='newphonebrand',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='new-phone-brand/'),
        ),
        migrations.AlterField(
            model_name='newphonecolor',
            name='hex_code',
            field=models.CharField(help_text='Color hex code (e.g., #FF5733)', max_length=7),
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='description_title',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description Title'),
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (optional)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='new-phone-model/'),
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='main_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Original price', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='memory',
            field=models.CharField(blank=True, help_text='e.g., 128GB', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='ram',
            field=models.CharField(blank=True, help_text='e.g., 8GB', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='notes',
            field=models.TextField(blank=True, default=1, help_text='Customer notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='phone_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='brandNew.newphonemodel'),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Final amount after discounts + shipping', max_digits=10),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_phone_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='website_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='website_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='newphonereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newphonereview',
            name='rating',
            field=models.PositiveIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='newphonereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='newphoneorder',
            index=models.Index(fields=['order_number'], name='brandNew_ne_order_n_fc4b77_idx'),
        ),
        migrations.AddIndex(
            model_name='newphoneorder',
            index=models.Index(fields=['status', 'payment_status'], name='brandNew_ne_status_1a0ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='newphoneorder',
            index=models.Index(fields=['-created_at'], name='brandNew_ne_created_d9001a_idx'),
        ),
        migrations.RemoveField(
            model_name='newphonemodel',
            name='color',
        ),
    ]
