# Generated by Django 5.2.7 on 2025-11-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0003_alter_newphonereview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newphonemodel',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
