# Generated by Django 5.2.7 on 2025-11-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0004_newphonemodel_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newphonemodel',
            options={'ordering': ['-rank'], 'verbose_name_plural': 'New Phone Models'},
        ),
    ]
