# Generated by Django 5.2.7 on 2025-11-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0005_alter_newphonemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newphonemodel',
            options={'ordering': ['-rank', '-id'], 'verbose_name_plural': 'New Phone Models'},
        ),
        migrations.AddField(
            model_name='newphoneorder',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
