# Generated by Django 5.2.7 on 2025-11-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0006_alter_newphonemodel_options_newphoneorder_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newphoneorder',
            old_name='shipping_cost',
            new_name='vat',
        ),
    ]
