# Generated by Django 5.2.7 on 2025-11-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0007_rename_shipping_cost_newphoneorder_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorStockManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available stock')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon_color_wise/')),
                ('color', models.ManyToManyField(related_name='stock_management', to='brandNew.newphonecolor')),
            ],
        ),
        migrations.AddField(
            model_name='newphonemodel',
            name='colors_stock',
            field=models.ManyToManyField(blank=True, related_name='phone_models', to='brandNew.colorstockmanagement'),
        ),
    ]
