# Generated by Django 5.2.7 on 2025-11-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0008_colorstockmanagement_newphonemodel_colors_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newphonemodel',
            name='colors_stock',
        ),
        migrations.CreateModel(
            name='StockManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available stock')),
                ('icon_color_based', models.ImageField(blank=True, null=True, upload_to='icon_color_based/')),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_management', to='brandNew.newphonemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='ColorStockManagement',
        ),
    ]
