# Generated by Django 5.2.7 on 2025-11-16 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0009_remove_newphonemodel_colors_stock_stockmanagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmanagement',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_management', to='brandNew.newphonecolor'),
        ),
    ]
