# Generated by Django 5.2.7 on 2025-11-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0010_stockmanagement_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmanagement',
            options={'ordering': ['phone_model', 'color'], 'verbose_name_plural': 'Stock Management'},
        ),
        migrations.AddField(
            model_name='stockmanagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmanagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmanagement',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Available stock', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockmanagement',
            unique_together={('phone_model', 'color')},
        ),
    ]
