# Generated by Django 5.2.7 on 2025-11-16 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0011_alter_stockmanagement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newphoneorder',
            name='stock_management',
            field=models.ForeignKey(default=1, help_text='Stock management entry (phone + color combination)', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='brandNew.stockmanagement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newphonemodel',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available stock (deprecated - use StockManagement)'),
        ),
    ]
