# Generated by Django 5.2.7 on 2025-11-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0012_newphoneorder_stock_management_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newphoneorder',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='country',
            field=models.CharField(blank=True, default='Bangladesh', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newphoneorder',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
