# Generated by Django 5.2.7 on 2025-11-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandNew', '0013_alter_newphoneorder_city_alter_newphoneorder_country_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newphonemodel',
            unique_together=set(),
        ),
    ]
