# Generated by Django 5.2.7 on 2025-11-02 09:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acsreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='acsreview',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='acsreview',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accessories.acsorder'),
        ),
        migrations.AlterField(
            model_name='acsreview',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='acsreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='acsreview',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
