# Generated by Django 5.2.7 on 2025-11-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_alter_acsreview_options_remove_acsreview_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsorder',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
