# Generated by Django 5.2.7 on 2025-11-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_acsorder_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acsorder',
            old_name='shipping_cost',
            new_name='vat',
        ),
    ]
